actor_rollout_ref:
  hybrid_engine: true
  model:
    path: Qwen/Qwen3-8B 
    lora_rank: 32
    use_shm: true
  actor:
    strategy: fsdp
    fsdp_config:
      activation_checkpointing: true
  rollout:
    name: vllm
    multi_turn: true
    max_steps: 100
    max_tokens: 8192
    temperature: 0.7
    top_p: 0.9
    load_format: safetensors
    tool_kwargs:
      tools_config_file: verl_tools/nano_tools.yaml

trainer:
  reward_fn: combined_reward
  batch_size: 32
  gradient_accumulation_steps: 4

resources:
  num_gpus: 4
  num_rollout_workers: 2
  rollout_gpu_per_worker: 1
  trainer_gpu: 2

output_dir: ./output/nano8b_ppo
