# VERL config for training Nano agent with sglang rollout engine
actor_rollout_ref:
  rollout:
    name: "sglang"
    multi_turn: true
    max_steps: 100        # Nano's default tool_limit
    max_tokens: 8192       # Nano's default token_limit
    tool_kwargs:
      tools_config_file: verl_tools/swe_tools.yaml
    
    # Temperature and sampling params to match Nano
    temperature: 0.7
    top_p: 0.9
    top_k: 20
    min_p: 0.0

trainer:
  reward_fn: combined_reward
  
  # Post-processors to attach metrics
  post_processors:
    - attach_diff      # Saves generated diff and computes similarity
    - cleanup_metrics  # Adds tool usage counts
  
  # PPO hyperparameters
  ppo:
    num_epochs: 4
    clip_ratio: 0.2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    
  # Training settings
  batch_size: 32
  gradient_accumulation_steps: 4
  learning_rate: 1e-5
  warmup_steps: 100
  
  # Checkpointing
  save_steps: 500
  save_total_limit: 5
  
  # Logging
  logging_steps: 10
  eval_steps: 100

# Resource allocation
resources:
  num_gpus: 8
  num_rollout_workers: 4
  rollout_gpu_per_worker: 1
  trainer_gpu: 4

# Output directory
output_dir: "./output/nano_swe_bench"